export const CHANGE_SOURCECODE = 'CHANGE_SOURCECODE'
export const CHANGE_BASECODE = 'CHANGE_BASECODE'
export const SELECT_SOURCE_COMPONENT = 'SELECT_SOURCE_COMPONENT'
export const SELECT_BASE_COMPONENT = 'SELECT_BASE_COMPONENT'